### ISSUE TITLE
cPolygon.cpython-36m-x86_64-linux-gnu.so: undefined symbol: alloca

### ISSUE THREAD

**Issue by stoneyang** [jraedler/Polygon3#3]
Hi, @jraedler 

I am using Polygon3 in my project, and I've encountered a problem after successfully installed it on a centos machine. 

```
Python 3.6.6rc1 (default, Jul 30 2018, 15:26:44)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Polygon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.local/lib/python3.6/site-packages/Polygon/__init__.py", line 5, in <module>
    from Polygon.cPolygon import *
ImportError: /home/.local/lib/python3.6/site-packages/Polygon/cPolygon.cpython-36m-x86_64-linux-gnu.so: undefined symbol: alloca
```

I have no clue on the `alloca` thing. Could you please give me some advice? 

Thanks in advance! 

Cheers!

**Comment by forrestr91** [comment]
我的python环境3.9.5，使用3.0.9.1遇到的一样的问题，更换为3.0.8好了，供参考。
